FROM node:lts

RUN npm install -g pnpm

WORKDIR /usr/src/app

RUN git clone https://github.com/Prometheus-X-association/dataspace-connector.git .

RUN pnpm i

#Copy env file and config file into docker
COPY ./images/provider-pdc/.env.production .
COPY ./images/provider-pdc/config.production.json ./src/config.production.json

#Command to run the application
CMD ["sh", "-c", "npm run build && npm run start"]
