# Use a base image with bash and gettext installed
FROM debian:bullseye-slim
# Install necessary packages
RUN apt-get update && \
    apt-get install -y gettext dos2unix jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# Set the working directory
WORKDIR /app
# Copy the script and any necessary files into the container
COPY prepare-seed.sh ./prepare-seed.sh
COPY .env ./.env
COPY images/mongodb-seed/template/ ./images/mongodb-seed/template/
# Make the script executable
RUN chmod +x ./prepare-seed.sh
# Command to execute the script and format the output
CMD ["bash", "-c", "./prepare-seed.sh"]