FROM node:lts
ARG FILE
ENV file=$FILE

RUN npm install -g pnpm

WORKDIR /usr/src/app

RUN git clone https://github.com/VisionsOfficial/sandbox-participant.git .

COPY ./images/example-api/$file .

#install dependency with --unsafe-perm to avoid bcrypt error
RUN npm install --unsafe-perm
